### ISSUE TITLE
Invoking start on StreamerLib crashes the application

### ISSUE THREAD

**Issue by Andreas1331** [neilyoung/android-videostreamdecodingsample-webrtc#2]
I've instantiated my StreamerLib using testing credentials from WebRTC Signaling Server inside the onCreate() function. I hooked the invocation of StreamerLib.Start() to a button, but when pressed the entire application crashes after a few seconds. I do get the status code 2 after instantiating my StreamerLib object, so it's all good up until I go through the signaling server.

I'm on Android 7.1.2 using a DJI Mavic 2 Enterprise. Any help is appreciated, thanks.

**Comment by neilyoung** [comment]
Difficult to guess. What application? My test app? Any adb log?

**Comment by Andreas1331** [comment]
It's my own application, but I extracted a snippet of your demo (this repository) from within the MainActivity.java file. Mainly the configuration of the StreamerLib object as well as the two events being triggered. Here's just a one liner from the Debug when invoking .start()
The entire thing is hundreds of lines, but I'm hoping this is enough otherwise I will put on pastebin or submit here.

`A/art: art/runtime/java_vm_ext.cc:470] JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.ClassNotFoundException: Didn't find class "org.webrtc.WebRtcClassLoader" on path: DexPathList[[zip file "/data/user/0/com.dji.GSDemo.Controller/.cache_sdk/sdkclasses2.jar", zip file "/data/user/0/com.dji.GSDemo.Controller/.cache_sdk/sdkclasses.jar", zip file "/system/framework/com.android.future.usb.accessory.jar", zip file "/data/app/com.dji.GSDemo.Controller-2/base.apk"],nativeLibraryDirectories=[/data/app/com.dji.GSDemo.Controller-2/lib/arm64, /data/app/com.dji.GSDemo.Controller-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]`

**Comment by Andreas1331** [comment]
I did try to clean my cache from within Android Studio - that did not help. However after adding the rule `
-keep class org.webrtc.** { *; }` to my proguard-rules.pro the error went away and it seems to establish a connection with the testing signaling server. I just don't see any video, just a blue screen on webrtcserver. In the WebRTC Internals I see both clients (the browser as well as the drone through the Android app).

**Comment by neilyoung** [comment]
You need to add your credentials in the webrtc server and then hit "Call" (once your Android application is started and has the StreamerLib also started. You should see the preview window on Android)

**Comment by Andreas1331** [comment]
The steps I took was: 
Log in using the same credentials on webrtcserver, now ready for the StreamerLib. The Android Application then instantiates the StreamerLib using the same credentials and invokes .start(). After this I hit "Call" on the webrtcserver, but unfortunately it does not work. I see errors now that I dig around the WebRTC Internals page:
icecandidateerror
`url: stun:numb.viagenie.ca:3478
address: x.x.x.x
port: 60148
host_candidate: x.x.x.x:60148
error_text: STUN binding request timed out.
error_code: 701`

**Comment by neilyoung** [comment]
You see the preview video in your Android app or don’t you use a Surface?

It is difficult to analyze STUN/TURN problems from outside. I don’t know about your network situation. That error is normal - not all candidates will work. 

Important is that there is a selected candidate pair in WebRTC internals. 

I would suggest to operate that first from both sides having on the same network

**Comment by Andreas1331** [comment]
Sorry for the late response, but yes being on the same network did the trick. Thanks for your help, Neil.

**Comment by neilyoung** [comment]
FYI: You don't necessarily have to be on the same network. You can provide your own STUN/TURN server if you think the internally used doesn't do the job. See https://github.com/neilyoung/djistreamerlib/wiki#custom-ice-server-configuration

**Comment by Andreas1331** [comment]
> FYI: You don't necessarily have to be on the same network. You can provide your own STUN/TURN server if you think the internally used doesn't do the job. See https://github.com/neilyoung/djistreamerlib/wiki#custom-ice-server-configuration

Yep that's true, and I did setup STUN/TURN servers as well which was fine. But the project was meant for internal close proximity use anyway so being on the same network was fine. Thank you.
